Gem::Specification.new do |s|
  s.name        = 'datawire-quark-core'
  s.version     = '0.0.1'
  s.summary     = 'Datawire Quark Core'
  s.description = 'Core runtime for Ruby code generated by Quark'
  s.author      = 'datawire.io'
  s.email       = 'hello@datawire.io'
  s.license     = 'Apache-2.0'
  s.files       = ['lib/datawire-quark-core.rb']
  s.homepage    = 'http://datawire.github.io/quark'
end
