#!/usr/bin/python
#
# Copyright 2015 datawire. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys, os

for f in sys.argv[1:]:
    name, ext = os.path.splitext(f)
    print "==%s==" % name
    if os.path.exists(name):
        os.system("diff -u %s %s" % (name, f))
    else:
        os.system("diff -u /dev/null %s" % f)
    st = raw_input()
    if st == "y":
        os.system("mv %s %s" % (f, name))
