# Copyright 2015 datawire. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from setuptools import setup

metadata = {}
with open("../../quark/_metadata.py") as fp:
    exec(fp.read(), metadata)
with open("quark_runtime.py") as fp:
    for line in fp:
        if line.startswith("__version__ = "):
            exec(line, metadata)
            break

setup(name="datawire-quark-core",
      version=metadata["__version__"],
      description="Core runtime for Python code generated by Quark",
      author=metadata["__author__"],
      author_email=metadata["__email__"],
      url=metadata["__uri__"],
      license=metadata["__license__"],
      py_modules=["quark_runtime"]
      )
